require(diversitree)
set.seed(5)
phy = tree.bd(c(.1,.03),max.taxa=100)
lik = make.bd(phy)
fit = find.mle(lik,c(.01,.03),method="subplex")
logLik(fit)
lik.yule=constrain(lik,mu~0)
fit.yule=find.mle(lik.yule,coef(fit)[1],method="subplex")
anova(fit,yule=fit.yule)
set.seed(1)
samples=mcmc(lik,fit$par, nsteps=10000,w=.1,print.every=0)
set.seed(1)
phy.sub=drop.tip(phy, sample(100,25))
lik.sub=make.bd(phy.sub,sampling.f=75/100)
fit.sub=find.mle(lik.sub,c(.1,.03),method="subplex")
coef(fit.sub)
lik.sub.yule=constrain(lik.sub,mu~0)
fit.sub.yule=find.mle(lik.sub.yule,coef(fit.sub)[1],method="subplex")
anova(fit.sub,yule=fit.sub.yule)
